SPECIES_LIST = [
    'Phoxinus',
    'Dyspanopeus sayi',
    'Orconectes limosus',
    'Pseudotsuga menziesii',
    'Fundulus heteroclitus',
    'Callinectes sapidus',
    'Trachemys scripta scripta',
    'Phoxinus septimaniae',
    'Batrachochytrium dendrobatidis',
    'Salmo trutta',
    'Pacifastacus leniusculus',
    'Phoxinus bigerri',
    'Oncorhynchus mykiss',
    'Silurus glanis',
    'Misgurnus anguillicaudatus',
    'Carassius auratus',
    'Trachemys scripta',
    'Gambusia holbrooki',
    'Senecio inaequidens',
    'Trachemys scripta elegans',
    'Dreissena polymorpha',
    'Cyprinus carpio',
    'Procambarus clarkii',
    'Neovison vison'
]